version: "3.8"

services:
  api:
    build: .
    container_name: poke-learning-api
    ports:
      - "8123:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./:/app
    environment:
      - ENVIRONMENT=production
